version: '3.1'

services:
  db:
    volumes:
      - broker_db:/var/lib/postgresql/data

  mq:
    ports:
      - "15672:15672"
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia/rabbit@mq

  restapi:
    ports:
      - "127.0.0.1:5687:5687"

  ttn_webhook:
    ports:
      - "127.0.0.1:5688:5688"

  pollers:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      - "db"
      - "mq"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "pollers.GreenBrain" ]

volumes:
  broker_db:
    external: true

  mq_data:
    external: true
