version: '3.1'

services:

  db:
    image: postgres
    restart: "no"
    env_file:
      - .env
    volumes:
      - ../db/init.d:/docker-entrypoint-initdb.d


  mq:
    hostname: "mq"
    image: rabbitmq:3-management
    restart: "no"
    logging:
      driver: "none"
    env_file:
      - .env


  restapi:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      - "db"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/restapi"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5687", "RestAPI:app" ]


  ttn_webhook:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      - "mq"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5688", "WebHook:app" ]


  ttn_decoder:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      - "db"
      - "mq"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "python", "AllMsgsWriter.py" ]


  lm:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    depends_on:
      - "db"
      - "mq"
    volumes:
      - ../src/python:/home/broker/python
    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "logical_mapper.LogicalMapper" ]


  x:
    image: broker/python-base
    restart: "no"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/home/broker/broker/src/python:/home/broker/broker/test/python
    depends_on:
      - "db"
      - "mq"
    volumes:
      - ..:/home/broker/broker
    working_dir: "/home/broker/broker"
    entrypoint: [ "./forever.sh" ]
