version: '3.1'

services:

  db:
    image: postgres
    restart: "no"
    env_file:
      - ../config/broker.env

    volumes:
      - broker_db:/var/lib/postgresql/data
      - ../db/init.d:/docker-entrypoint-initdb.d

  mq:
    hostname: "mq"
    image: rabbitmq:3-management
    restart: "no"

    env_file:
      - ../config/broker.env

    ports:
      - "15672:15672"

    volumes:
     - mq_data:/var/lib/rabbitmq/mnesia/rabbit@mq


  restapi:
    image: broker/python-base
    restart: "unless-stopped"
    env_file:
      - ../config/broker.env

    ports:
      - "5687:5687"

    depends_on:
      - "db"


    volumes:
      - ../src/python:/home/broker/python

    working_dir: "/home/broker/python/restapi"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5687", "RestAPI:app" ]

  ttn_webhook:
    image: broker/python-base
    restart: "unless-stopped"
    env_file:
      - ../config/broker.env

    ports:
      - "5688:5688"

    depends_on:
      - "mq"

    volumes:
      - ../src/python:/home/broker/python

    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "/home/broker/.local/bin/uvicorn", "--proxy-headers", "--host", "0.0.0.0", "--port", "5688", "WebHook:app" ]

  ttn_decoder:
    image: broker/python-base
    restart: "no"
    env_file:
      - ../config/broker.env

    depends_on:
      - "db"
      - "mq"

    volumes:
     - ../src/python:/home/broker/python

    working_dir: "/home/broker/python/ttn"
    entrypoint: [ "python", "AllMsgsWriter.py" ]


  lm:
    image: broker/python-base
    restart: "no"
    env_file:
      - ../config/broker.env

    depends_on:
      - "db"
      - "mq"

    volumes:
     - ../src/python:/home/broker/python

    working_dir: "/home/broker/python"
    entrypoint: [ "python", "-m", "logical_mapper.LogicalMapper" ]


volumes:
  broker_db:
    external: true

  mq_data:
    external: true
