global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'restapi'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'restapi:8000' ]
  - job_name: 'ttn_webhook'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'ttn_webhook:8001']
