apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/compose-default: "true"
    io.kompose.service: ttn-decoder
  name: ttn-decoder
spec:
  containers:
    - command:
        - node
        - src
      env:
        - name: DATABOLT_SHARED_DIR
          valueFrom:
            configMapKeyRef:
              key: DATABOLT_SHARED_DIR
              name: env
        - name: GREENBRAIN_PASSWORDS
          valueFrom:
            configMapKeyRef:
              key: GREENBRAIN_PASSWORDS
              name: env
        - name: GREENBRAIN_USERS
          valueFrom:
            configMapKeyRef:
              key: GREENBRAIN_USERS
              name: env
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              key: PGDATABASE
              name: env
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              key: PGHOST
              name: env
        - name: PGPASSWORD
          valueFrom:
            configMapKeyRef:
              key: PGPASSWORD
              name: env
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              key: PGPORT
              name: env
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              key: PGUSER
              name: env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: env
        - name: PYTHONPATH
          valueFrom:
            configMapKeyRef:
              key: PYTHONPATH
              name: env
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_DEFAULT_PASS
              name: env
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_DEFAULT_USER
              name: env
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_HOST
              name: env
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_PORT
              name: env
        - name: TTN_API_TOKEN
          valueFrom:
            configMapKeyRef:
              key: TTN_API_TOKEN
              name: env
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: env
        - name: UBIDOTS_API_TOKEN
          valueFrom:
            configMapKeyRef:
              key: UBIDOTS_API_TOKEN
              name: env
      image: sampixelyork/ttn_decoder:latest
      name: ttn-decoder
      resources: {}
      volumeMounts:
        - mountPath: /usr/src/ttn_decoder/src
          name: ttn-decoder-claim0
        - mountPath: /usr/src/ttn_formatters
          name: ttn-decoder-claim1
      workingDir: /usr/src/ttn_decoder
  restartPolicy: Never
  volumes:
    - name: ttn-decoder-claim0
      persistentVolumeClaim:
        claimName: ttn-decoder-claim0
    - name: ttn-decoder-claim1
      persistentVolumeClaim:
        claimName: ttn-decoder-claim1
status: {}
