---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - URL=broker-staging.farmdecisiontech.net.au
      - VALIDATION=http
    volumes:
      - /root/Swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  iota:
    image: twinfield89/dpi-device-manager
    ports:
        - '5000:5000'
    environment:
        - bearer_token=ive_h3@ard_a_l0ng_sentence_is_as_good_@s_anyth1ng
        - 'end_point=https://iot.farmdecisiontech.net.au'
