apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:14.2
          env:
          - name: db_init
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: DB_INIT
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: PGDATABASE
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: PGUSER
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -q
                - -d
                - ${PGDATABASE}
                - -U
                - ${PGUSER}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: init-script
          hostPath:
            path: db_init
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
