apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: broker/python-base:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - name: python-src-volume
          mountPath: /home/broker/python
        workingDir: /home/broker/python
        command:
#          - sh
#          - -c
#          - tail -f /dev/null
          - python
          - -m
          - delivery.UbidotsWriter
#        command: ["sh", "-c", "python", "-m", "delivery.UbidotsWriter"]
      volumes:
      - name: python-src-volume
        hostPath:
          path: /home/broker/src/python
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
spec:
  selector:
    app: delivery
  ports:
  - name: http
    port: 80
    targetPort: 80
