apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: sampixelyork/python-base:latest
        env:
        - name: PYTHON_SRC_PATH
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: PYTHON_SRC_PATH
        volumeMounts:
        - name: python-src-volume
          mountPath: /home/broker/python
        workingDir: /home/broker/python
        command: ["python"]
        args: ["-m", "delivery.UbidotsWriter"]
      volumes:
      - name: python-src-volume
        hostPath:
          path: /${PYTHON_SRC_PATH}
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
spec:
  selector:
    app: delivery
  ports:
  - name: http
    port: 80
    targetPort: 80
