apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: broker/python-base:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
              name: env-configmap
          workingDir: /home/broker/python
          command:
            - python
            - -m
            - delivery.UbidotsWriter
          volumeMounts:
            - name: shared-data
              mountPath: /home/broker/python
      volumes:
        - name: shared-data
          hostPath:
            path: /opt/broker/src/python