apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello-world
  template:
    metadata:
      labels:
        app: python-hello-world
    spec:
      containers:
      - name: python
        image: python:latest
        command: ["python"]
        args: ["-c", "print('Hello, world!')"]
