apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttn-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttn-webhook
  template:
    metadata:
      labels:
        app: ttn-webhook
    spec:
      containers:
      - name: ttn-webhook
        image: broker/python-base:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - name: python-src-volume
          mountPath: /home/broker/python
        workingDir: /home/broker/python/ttn
        command:
          - /home/broker/.local/bin/uvicorn
          - --proxy-headers
          - --host
          - 0.0.0.0
          - --port
          - "5688"
          - WebHook:app
      volumes:
      - name: python-src-volume
        hostPath:
          path: /home/broker/src/python
---
apiVersion: v1
kind: Service
metadata:
  name: ttn-webhook
spec:
  selector:
    app: ttn-webhook
  ports:
  - name: http
    port: 5688
    protocol: TCP
    targetPort: 5688
