apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttn-decoder
spec:
  selector:
    matchLabels:
      app: ttn-decoder
  replicas: 1
  template:
    metadata:
      labels:
        app: ttn-decoder
    spec:
      containers:
        - name: ttn-decoder
          image: broker/ttn_decoder:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: env-configmap
          volumeMounts:
            - name: ttn-decoder-volume
              mountPath: /usr/src/ttn_decoder/src
            - name: ttn-formatters-volume
              mountPath: /usr/src/ttn_formatters
          workingDir: "/usr/src/ttn_decoder"
          command:
#            - sh
#            - -c
            - node
            - src
      volumes:
        - name: ttn-decoder-volume
          hostPath:
            path: /home/broker/src/js/ttn_decoder/src
        - name: ttn-formatters-volume
          hostPath:
            path: /home/ttn-formatters
---
apiVersion: v1
kind: Service
metadata:
  name: ttn-decoder-service
spec:
  selector:
    app: ttn-decoder
  ports:
    - name: http
      port: 80
      targetPort: 80
