apiVersion: apps/v1
kind: Deployment
metadata:
  name: wombat
spec:
  selector:
    matchLabels:
      app: wombat
  replicas: 1
  template:
    metadata:
      labels:
        app: wombat
    spec:
      containers:
      - name: wombat
        image: sampixelyork/python-base:latest
        env:
        - name: PYTHON_SRC_PATH
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: PYTHON_SRC_PATH
        volumeMounts:
        - name: python-src-volume
          mountPath: /home/broker/python
        workingDir: /home/broker/python
        command: ["python"]
        args: ["-m", "ydoc.Wombat"]
      volumes:
      - name: python-src
        hostPath:
          path: /${PYTHON_SRC_PATH}
---
apiVersion: v1
kind: Service
metadata:
  name: wombat
spec:
  selector:
    app: wombat
  ports:
  - name: http
    port: 80
    targetPort: 80
