apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-deployment
spec:
  selector:
    matchLabels:
      app: x
  replicas: 1
  template:
    metadata:
      labels:
        app: x
    spec:
      containers:
        - name: x
          image: broker/python-base:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
              name: env-configmap
          workingDir: /home/broker
          command:
            - ./forever.sh
          volumeMounts:
            - name: shared-data
              mountPath: /home/broker/python
      volumes:
        - name: shared-data
          hostPath:
            path: /opt/broker/src/python
