apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ydoc
  template:
    metadata:
      labels:
        app: ydoc
    spec:
      containers:
      - name: ydoc
        image: broker/python-base:latest
        imagePullPolicy: Never
        env:
        - name: python_src_path
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: PYTHON_SRC_PATH
        volumeMounts:
        - name: python-src-volume
          mountPath: /home/broker/python
        workingDir: "/home/broker/python"
        command: ["python"]
        args: ["-m", "ydoc.YDOC"]
      volumes:
      - name: python-src-volume
        hostPath:
          path: python_src_path
---
apiVersion: v1
kind: Service
metadata:
  name: ydoc
spec:
  selector:
    app: ydoc
  ports:
  - name: http
    port: 80
    targetPort: 80
