apiVersion: apps/v1
kind: Deployment
metadata:
  name: lm
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lm
  template:
    metadata:
      labels:
        app: lm
    spec:
      containers:
        - name: lm
          image: broker/python-base
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          workingDir: /home/broker/python
          command:
            - python
            - -m
            - logical_mapper.LogicalMapper
          volumeMounts:
            - name: shared-data
              mountPath: /home/broker/python
      volumes:
        - name: shared-data
          hostPath:
            path: /opt/broker/src/python
