apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt_processors
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt_processors
  template:
    metadata:
      labels:
        app: mqtt_processors
    spec:
      containers:
        - name: mqtt_processors
          image: broker/python-base
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          workingDir: /home/broker/python
          command:
            - python
            - -m
            - mqtt_processors.MQTTProcessors
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-data
              mountPath: /home/broker/python
      volumes:
        - name: shared-data
          hostPath:
            path: /opt/broker/src/python
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt_processors
  namespace: broker
spec:
  selector:
    app: mqtt_processors
  ports:
    - name: prometheus
      port: 8000
