apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttn-processor
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttn-processor
  template:
    metadata:
      labels:
        app: ttn-processor
    spec:
      containers:
        - name: ttn-processor
          image: broker/python-base:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-configmap
          workingDir: /home/broker/python/ttn
          command:
            - python
            - AllMsgsWriter.py
          volumeMounts:
            - name: shared-data
              mountPath: /home/broker/python
      volumes:
        - name: shared-data
          hostPath:
            path: /opt/broker/src/python
