apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-src-path
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: python-src-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-src-path
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/sam/csu-dpi/broker/src/python
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  volumeMode: Filesystem
